Finalização do projeto - Pedro Marino
rtio/landing-page-challenge pull request #4
Opened 2023-04-26 21:15 UTC by pedromarino07

Apresentação do projeto - Pedro Marino Viana Lima.

2023-05-01 23:26 UTC, rtio requested changes
Remova as acentuações dos nomes das classes e não remover a licença. Fora esses pequenos detalhes tudo está ok!

2023-05-01 23:26 UTC, rtio commented on index.html
> +      <ul class="cabeçalho">
aqui

2023-05-01 23:26 UTC, rtio commented on index.html
> +    <section class="título">
aqui

2023-05-01 23:26 UTC, rtio commented on index.html
> +    <section class="descrição">
aqui

2023-05-01 23:26 UTC, rtio commented on index.html
> +        <thead class="informação">
aqui

2023-05-01 23:26 UTC, rtio commented on index.html
> +        <tbody class="informação2">
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> -/* default color variables */
Licença não deve ser removida.

2023-05-01 23:26 UTC, rtio commented on style.css
> +.cabeçalho{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.cabeçalho a{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.título{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.título h1{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.título p{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.título a{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.título a:hover{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.descrição h2{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.informação{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.informação th{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.informação2{
aqui

2023-05-01 23:26 UTC, rtio commented on style.css
> +.informação2 td{
aqui

2023-05-03 21:03 UTC, pedromarino07 commented
Feita a correção conforme solicitado.

2023-05-07 15:27 UTC, rtio commented on style.css
> +    border-radius: 2px;
```suggestion
    border-radius: 0.25rem;
```

2023-05-07 15:27 UTC, rtio approved these changes
Ótimo

2023-05-07 15:28 UTC, closed without merging